### ISSUE TITLE
params->size is not set in unpack.c

### ISSUE THREAD

**Issue by bontric** [splone/splonebox-core#1]
The _size_ field of `params` (`message_params_object`) needs to be set.

``` c
//... (Line 81)
 /* if array is empty return success */
  if (obj->via.array.size <= 0) {
    params->obj = NULL;
    params->size = 0;
    return (0);
  }

  params->obj = CALLOC(obj->via.array.size, struct message_object);
// ...
```

The following line should be added after allocating the memory.

``` c
params->size = obj->via.array.size;
```

**Comment by stze** [comment]
The _size_ of `params` is set. _size_ only needs to be set if params is `NULL`. Maybe you misread the following line (memory allocation):

`params->obj = CALLOC(obj->via.array.size, struct message_object);`

not `message_params_object` is allocated, a `message_object` is allocated, so no `size` needs to be set.

close?

**Comment by bontric** [comment]
Okay, maybe I should've said something about the context.

`unpack_params` is called by `message_deserialize_request` (message.c:204) and is therefore used to "pack"  the `message_request` struct. 

> The size of params is set. 

Where?

> size only needs to be set if params is NULL

If that is true. We shouldn't check for param's size in `dispatch.c` (line 51)

``` c
/* check params size */
  if (request->params.size != 2) {
    error_set(api_error, API_ERROR_TYPE_VALIDATION,
        "Error dispatching register API request. Invalid params params size");
    return (-1);
  }
```

Just to clarify: The problem is that the splonebox-core drops a valid request because this value is not set. Adding the line mentioned above, fixes that issue.

**Comment by stze** [comment]
you are right. the `size` parameter needs to be set. sry, i've replied to fast.
