### ISSUE TITLE
Segfault in handle_run 

### ISSUE THREAD

**Issue by bontric** [splone/splonebox-core#16]
The function `handle_run` (Commit a0e82f4603427b661926ec994acd7a2523d910b) will cause a segfault if the target plugin does not exist.

The problem is, that `cinfo` is not checked before usage.

``` c
 cinfo = connection_send_request(pluginlongtermpk, cstring_copy_string("run"),
      params, api_error);

  if (cinfo->response->params.size != 1) {
    error_set(api_error, API_ERROR_TYPE_VALIDATION,
        "Error dispatching run API response. Invalid params size");
    return (-1);
  }
```

`cinfo` might be `NULL` though.. (a0e82f4603427b661926ec994acd7a2523d910b9)

``` c
// connection_send_request
//...

  if (!con) {
    error_set(api_error, API_ERROR_TYPE_VALIDATION, "plugin not registered");
    return (NULL);
  }
```

**Comment by mkind** [comment]
Good point. We should fix this before merging into master branch.
