### ISSUE TITLE
Unit test for `message_deserialize_response`

### ISSUE THREAD

**Issue by mkind** [splone/splonebox-core#34]
Unit test for `message_deserialize_response` is missing.

**Comment by denji** [comment]
- [src/api/apikey.c:38]: (error) Resource leak: f
- [src/rpc/connection/server.c:148]: (error) Uninitialized variable: server
- [src/string.c:41] -> [src/string.c:38]: (warning) Possible null pointer dereference: str - otherwise it is redundant to check it against null.

**Comment by stze** [comment]
Thanks @denji and cppcheck for reporting this. I'll add a `fclose(f)` in _src/api/apikey.c_ to close the file descriptor  if `fread` function fails.  The _server.c:148_ error and the warning in _src/string.c:41_ are cppcheck false positives.
