### ISSUE TITLE
Config File support

### ISSUE THREAD

**Issue by mkind** [splone/splonebox-core#37]
We need support for a config file. There are different types of config files: 
1. XML
2. ini style
3. [libconfig style](http://www.hyperrealm.com/libconfig/test.cfg.txt)
4. rc style [**preferred**]

**Comment by stze** [comment]
i like tor-rc style config

**Comment by stze** [comment]
configuration option wiki can be found [here](https://github.com/splone/splonebox-core/wiki/User-manual).

**Comment by mkind** [comment]
Done in v0.1.5.
