### ISSUE TITLE
Make static functions unit-testable

### ISSUE THREAD

**Issue by stze** [splone/splonebox-core#42]
`static` functions are currently not testable. we need some improvements to make this happen:
- Add a macro to disable `static` keyword in function prototype and declaration:

``` c
#ifdef BOX_UNIT_TESTS
#define STATIC
#else
#define STATIC static
#endif
```
- enable `BOX_UNIT_TESTS` compile option in `sb-test` cmake target
- move prototypes of `static` functions to a header file, e.g. for `connection.c` we would add a `connection.h` header file and add all prototypes:

``` c
STATIC void close_cb(uv_handle_t *handle);
STATIC int connection_handle_request(struct connection *con,
    msgpack_object *obj);
STATIC int connection_handle_response(struct connection *con,
    msgpack_object *obj);
STATIC void connection_request_event(connection_request_event_info *info);
STATIC void connection_close(struct connection *con);
STATIC int parse_cb(inputstream *istream, void *data, bool eof);
```
- include connection.h in test, finished

**Comment by mkind** [comment]
@stze, can we close the issue?
