### ISSUE TITLE
libcurl integration for elasticsearch database queries

### ISSUE THREAD

**Issue by stze** [splone/splonebox-core#48]
Elasticsearch provides a full Query DSL based on JSON to define queries. For example, searching all documents across all types within an example twitter index would use the following query:

``` bash
$ curl -XGET 'http://localhost:9200/twitter/_search?q=user:kimchy'
```

To create queries from C language we need to integrate _libcurl_.

**Comment by mkind** [comment]
Since database integration is done via plugin, this core issue is obsolete.
