### ISSUE TITLE
functional_db_function_verify fails

### ISSUE THREAD

**Issue by mkind** [splone/splonebox-core#7]
Pulling master, compiling and starting tests results in `functional_db_function_verify` to fail.

```
[ RUN      ] functional_db_function_verify
sb-test: Invalid argument count!
sb-test: Invalid argument count!
0 == 0
../test/functional/db-function-verify.c:78: error: Failure!

[  FAILED  ] functional_db_function_verify
```

**Comment by bontric** [comment]
See #4 , tests have to be adjusted accordingly. :octopus:

**Comment by mkind** [comment]
Hm. There must be no failing tests in the master branch! I'll have a look at the details.
